---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'teams//$Action/': 'Basil\Controller\TeamController'
    'players//$Action/': 'Basil\Controller\PlayerController'